# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b4d6bbe9dbb3c16eff4b68013e1cf5d9715a2e2258ee21a3cc5a1f879bef85b5316a8cd96521a9c2fa23152111413ff6e4b89bc36df92f47329126e21291020

test:
  secret_key_base: 03421a7811ea54a349541fd174d7a6b05c15f05ccfb4118c983704cab2b55735e3d3abc118bcc515842318a9e9670efe41a5683845d9c2a321ef5cc9339487ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
